export { getArray } from './functions/getArray/getArray'
export { sequencedForEach } from './functions/sequencedForEach/sequencedForEach'
export { isFunction } from './functions/isFunction/isFunction'
export { pipe } from './functions/pipe/pipe'
export { compose } from './functions/compose/compose'
export { once } from './functions/once/once'
export { getRandomInteger } from './functions/getRandomInteger/getRandomInteger'
